import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter_fine_dust/model/status_model.dart';

final statusLevel = [
  StatusModel(
    level: 0,
    label: '좋음',
    primaryColor: Color(0xff32a1ff),
    subColor: Color(0xffcce7ff),
    fontColor: Colors.white,
    imgUrl: 'assets/img/best.svg',
    comment: '상쾌한 날이에요~',
    minFineDust: 0,
    minUltraFineDust: 0,
    minO3: 0,
    minNO2: 0,
    minCO: 0,
    minSO2: 0,
  ),
  StatusModel(
    level: 1,
    label: '보통',
    primaryColor: Color(0xFF00C73C),
    subColor: Color(0xFFBFF1CE),
    fontColor: Colors.white,
    imgUrl: 'assets/img/smile.svg',
    comment: '평범하네요',
    minFineDust: 31,
    minUltraFineDust: 16,
    minO3: 0.031,
    minNO2: 0.031,
    minCO: 2.1,
    minSO2: 0.021,
  ),
  StatusModel(
    level: 2,
    label: '나쁨',
    primaryColor: Color(0xfffd9b5a),
    subColor: Color(0xfffee6d6),
    fontColor: Colors.white,
    imgUrl: 'assets/img/bad.svg',
    comment: '나쁜 날이네요',
    minFineDust: 81,
    minUltraFineDust: 36,
    minO3: 0.091,
    minNO2: 0.061,
    minCO: 9.1,
    minSO2: 0.051,
  ),
  StatusModel(
    level: 3,
    label: '매우나쁨',
    primaryColor: Color(0xffde5b61),
    subColor: Color(0xffffd1d3),
    fontColor: Colors.white,
    imgUrl: 'assets/img/very_bad.svg',
    comment: '심각합니다.',
    minFineDust: 151,
    minUltraFineDust: 76,
    minO3: 0.151,
    minNO2: 0.201,
    minCO: 15.1,
    minSO2: 0.151,
  ),
];
